### ISSUE TITLE
No documentation for what localhost:8088 should be running

### ISSUE THREAD

**Issue by matievisthekat** [CodyJones4235/PoopMap#5]
Trying to log in on a locally hosted version results in this error:
```
GET http://localhost:8088/users?email=<my email> net::ERR_CONNECTION_REFUSED
```
which is understandable since I have nothing running on port 8088.

What server do I need to run on port 8088 to host a fully functioning version of this site?

**Comment by cody-jones-imprivata** [comment]
this project was made with[ json-server](https://www.npmjs.com/package/json-server) so if you want to run it you have to install json-server and drop in your own data. This was my first react project so its not the best with documentation, I have plans to update it

**Comment by cody-jones-imprivata** [comment]
> this project was made with[ json-server](https://www.npmjs.com/package/json-server) so if you want to run it you have to install json-server and drop in your own data. This was my first react project so its not the best with documentation, I have plans to update it

I have added a `database.json` so if you pull main and run `npm start` & `json-server -p 8088 database.json` you should be able to see some posts and comments
